const API_BASE_URL = "https://hub.docker.com";
const API_VERSION = "v2";

const TAGS_PAGE_DEFAULT = 1;
const TAGS_PER_PAGE_DEFAULT = 100;

export { TAGS_PAGE_DEFAULT, TAGS_PER_PAGE_DEFAULT, API_VERSION, API_BASE_URL };
